openapi: "3.0.0"

info:
  title: ExcelConverter
  version: "1.0"
servers:
  - url: http://localhost:5000/v1.0

paths:
  /compare/{name}:
    post:
      summary: compare source file headers with database
      description: compare headers
      operationId: compare
      responses:
        200:
          description: columns from db, target column numbers, user_id
          content:
            text/plain:
              schema:
                type: string
                example: ["szöveg1", szöveg2]
      parameters:
        - name: texts
          in: form
          description: list of header text of columns
          required: true
          schema:
            type: string
            example: "dave"